-- ========================================
-- Script: add_surrogatekey_to_fact_table
-- Purpose: Generating surrogate key
-- Author: Daniel Varga
-- Created: 2025-08-05
-- Modified: 2025-08-05
-- ========================================


-- Creating a new fact table that includes a surrogate key generated by combining multiple columns
CREATE TABLE gold.fact_departure_data_new AS
SELECT
  ROW_NUMBER() OVER (ORDER BY date_fk, tail_num_fk, mkt_unique_carrier, mkt_carrier_fl_num, origin_id, dest_id) AS flight_id,
  *
FROM gold.fact_departure_data;

--Dropping old table 
DROP TABLE gold.fact_departure_data;

--Renaming new table 
ALTER TABLE gold.fact_departure_data_new RENAME TO fact_departure_data;